### PR TITLE
Create Wolfgang.rst

### PR DESCRIPTION
**Pull request by WA-2344**
Wolfgang
======

* Time – any time on button click you can produce a new documentation version in just a few minutes
* Developer friendly > devs don‘t have to leave their IDEs
* Versioning and traceability
* Separation of form and content
* Reusing of contents
* Low price due to open source

### CODE REVIEW

**Comment by WA-2344** [comment]
Fertig.

**Review by WA-2344 — COMMENTED** [review]
Fertig.

**Comment by WA-2344** [comment]
Wirklich fertig?

**Review by IgorV97 — CHANGES_REQUESTED** [review]
Passt nicht, da ist ja gar kein INHALT!

**Review by IgorV97 — APPROVED** [review]

**Review by IgorV97 — APPROVED** [review]

**Pull request merged**
